/*
SQLyog Ultimate v12.5.1 (32 bit)
MySQL - 10.4.27-MariaDB
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

create table `assesmen_dokters` (
	`id` bigint (20),
	`created_at` timestamp ,
	`updated_at` timestamp ,
	`id_kunjungan` varchar (765),
	`id_pasien` varchar (765),
	`id_asskep` varchar (765),
	`pic` varchar (765),
	`tgl_entry` timestamp ,
	`tgl_kunjungan` timestamp ,
	`tgl_pemeriksaan` timestamp ,
	`sumber_data` varchar (765),
	`tekanan_darah` varchar (765),
	`frekuensi_nadi` varchar (765),
	`frekuensi_nafas` varchar (765),
	`suhu_tubuh` varchar (765),
	`riwayat_alergi` varchar (765),
	`keterangan_alergi` varchar (765),
	`riwayat_kehamilan_pasien_wanita` varchar (765),
	`riwyat_kelahiran_pasien_anak` varchar (765),
	`riwyat_penyakit_sekarang` varchar (765),
	`hipertensi` varchar (765),
	`kencingmanis` varchar (765),
	`jantung` varchar (765),
	`stroke` varchar (765),
	`hepatitis` varchar (765),
	`asthma` varchar (765),
	`ginjal` varchar (765),
	`tbparu` varchar (765),
	`riwayatlain` text ,
	`statusgeneralis` text ,
	`keadaanumum` text ,
	`kesadaran` text ,
	`diagnosakerja` text ,
	`diagnosabanding` text ,
	`rencanakerja` text ,
	`vd_od` varchar (765),
	`vd_od_pinhole` varchar (765),
	`vd_os` varchar (765),
	`vd_os_pinhole` varchar (765),
	`refraktometer_od_sph` varchar (765),
	`refraktometer_od_cyl` varchar (765),
	`refraktometer_od_x` varchar (765),
	`refraktometer_os_sph` varchar (765),
	`refraktometer_os_cyl` varchar (765),
	`refraktometer_os_x` varchar (765),
	`Lensometer_od_sph` varchar (765),
	`Lensometer_od_cyl` varchar (765),
	`Lensometer_od_x` varchar (765),
	`Lensometer_os_sph` varchar (765),
	`Lensometer_os_cyl` varchar (765),
	`Lensometer_os_x` varchar (765),
	`koreksipenglihatan_vod_sph` varchar (765),
	`koreksipenglihatan_vod_cyl` varchar (765),
	`koreksipenglihatan_vod_x` varchar (765),
	`koreksipenglihatan_vos_sph` varchar (765),
	`koreksipenglihatan_vos_cyl` varchar (765),
	`koreksipenglihatan_vos_x` varchar (765),
	`tajampenglihatandekat` text ,
	`tekananintraokular` text ,
	`catatanpemeriksaanlain` text ,
	`palpebra` text ,
	`konjungtiva` text ,
	`kornea` text ,
	`bilikmatadepan` text ,
	`pupil` text ,
	`iris` text ,
	`lensa` text ,
	`funduskopi` text ,
	`status_oftamologis_khusus` text ,
	`masalahmedis` text ,
	`prognosis` text ,
	`gambar1` blob ,
	`gambar2` blob ,
	`keluhan_pasien` varchar (765),
	`signature` text ,
	`status` varchar (765)
);
